# Generated by Django 4.2.13 on 2024-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendanceentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="topic",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
