# Generated by Django 4.2.13 on 2024-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_alter_topic_options_topic_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceentry",
            name="selfie",
            field=models.ImageField(blank=True, null=True, upload_to="selfies/"),
        ),
    ]
