# Generated by Django 4.2.13 on 2024-08-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_attendanceentry_selfie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceentry",
            name="selfie",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
