# Generated by Django 4.2.13 on 2024-09-11 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alter_attendanceentry_selfie"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceentry",
            name="device_identifier",
            field=models.CharField(
                default="2024-09-11 13:45:30.123456+00:00", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceentry",
            name="submission_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
